### ISSUE TITLE
Routed Pipelines should be problematic

### ISSUE THREAD

**Issue by peter279k** [antidot-framework/antidot-docs#6] opened 2021-01-18 18:37 UTC
**Describe the bug**
I think the Routed Pipelines steps are not completed.

**To Reproduce**
1. Using `composer create-project antidot-fw/antidot-framework-starter project-name` command.
2. Creating the `./src/Application/Http/Handler/ApiPage.php` request handler class.

The `ApiPage` contents are as follows:

```PHP
<?php

declare(strict_types=1);

namespace App\Application\Http\Handler;

use App\Application\Event\SomeEvent;
use Psr\EventDispatcher\EventDispatcherInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Laminas\Diactoros\Response\JsonResponse;

class ApiPage implements RequestHandlerInterface
{
    /** @var EventDispatcherInterface */
    private $eventDispatcher;

    public function __construct(EventDispatcherInterface $eventDispatcher)
    {
        $this->eventDispatcher = $eventDispatcher;
    }

    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        $this->eventDispatcher->dispatch(SomeEvent::occur());

        return new JsonResponse([
            'docs' => 'https://antidotfw.io',
            'Message' => 'Welcome to Antidot Framework Starter'
        ]);
    }
}

```

3. Adding the `App\Application\Http\Handler\ApiPage:` on `./config/services/dependencies.prod.yaml` file. And file contents are:

```
services:
  App\Application\Http\Handler\HomePage:
  App\Application\Http\Handler\ApiPage:
  App\Application\Http\Handler\SomeMiddleware:
  App\Application\EventListener\SomeEventListener:
    tags:
      - { name: 'event_listener', event: 'App\Application\Event\SomeEvent' }

  some.command:
    class: App\Application\Command\SomeCommandExample
    tags:
      - { name: 'console.command', command: 'my:custom:command' }

parameters:
  debug: true
  config_cache_enabled: false
  monolog:
    handlers:
      default:
        type: 'stream'
        options:
          stream: 'var/log/%date%-default.log'
          level: 400

```
4. And routes.php contents are:

```php
<?php

declare(strict_types=1);

use Antidot\Application\Http\Application;
use App\Application\Http\Handler\HomePage;
use App\Application\Http\Handler\ApiPage;
use App\Application\Http\Handler\SomeMiddleware;
use Psr\Container\ContainerInterface;

/**
 * Setup routes with a single request method:
 *
 * $app->get('/', App\Handler\HomePageHandler::class, 'home');
 * $app->post('/album', App\Handler\AlbumCreateHandler::class, 'album.create');
 * $app->put('/album/:id', App\Handler\AlbumUpdateHandler::class, 'album.put');
 * $app->patch('/album/:id', App\Handler\AlbumUpdateHandler::class, 'album.patch');
 * $app->delete('/album/:id', App\Handler\AlbumDeleteHandler::class, 'album.delete');
 *
 * Or with multiple request methods:
 *
 * $app->route('/contact', App\Handler\ContactHandler::class, ['GET', 'POST', ...], 'contact');
 */
return static function (Application $app, ContainerInterface $container) : void {
    $app->get('/', [SomeMiddleware::class, HomePage::class], 'home');
    $app->get('/api', [SomeMiddleware::class, ApiPage::class], 'api');
};

```

**Expected behavior**
It will be worked for requesting the `/api` route with `GET` method.

**Screenshots**
The error log is as follows and it's available on `./var/log/` folder:
`[2021-01-19T02:29:03.544855+08:00] default.ERROR: {"message":"Invalid handler name name given App\\Application\\Http\\Handler\\ApiPage.","code":0,"file":"\/data\/cloud-printer-api\/vendor\/antidot-fw\/framework\/src\/Application\/Http\/Handler\/LazyLoadingRequestHandler.php","line":35} [] []`

**Additional context**
N/A.

**Comment by kpicaza** [comment] 2021-01-18 18:46
Hi @peter279k thanks for reporting, I'm preparing a test project to reproduce it, but it looks like a common mistake with cached config:
* check `var/cache/` directory if there is some PHP file, if there is delete it, it will regenerate in the next page reload
* enable development mode to see configuration changes after reload `bin/console config:development-mode`
* you can see available services running `bin/console config:show:container`

**Comment by kpicaza** [comment] 2021-01-18 19:01
@peter279k After testing the same steps, I think the problem is the cached config(I have the same error when I load a page before adding a new service to config and then loading this service), I think there are two problems here: the first thing I need to explain the cached config behavior, and the second, the exception message doesn't help too much. Thanks for reporting :rocket::rocket: :rocket:

**Comment by kpicaza** [comment] 2021-01-18 19:19
https://github.com/antidot-framework/antidot-docs/issues/7
https://github.com/antidot-framework/container/issues/20

**Comment by peter279k** [comment] 2021-01-19 10:49
Thanks for your reply.

I think it should have some steps about creating new route routines or troubleshooting :).

It can add some tips like that:

```
check var/cache/ directory if there is some PHP file, if there is delete it, it will regenerate in the next page reload
```

**Comment by kpicaza** [comment] 2021-01-24 11:18
Closing in favor of https://github.com/antidot-framework/antidot-docs/issues/7

**Closed as completed by kpicaza** 2021-01-24 11:18 UTC
Labels: bug
